#!/usr/bin/env sh

pid=$(pidof qtcreator-bin)

# find existing creator instance
if [[ "${pid}" != "" ]]; then
  creatorbin=$(ls -l /proc/${pid}/exe | awk '{ print $11 }')
  ${creatorbin} -client $@
  exit 0
fi

# failing that run the creator in your path
qtcreator.sh $@
exit 0
